### ISSUE TITLE
7. List the members of the batch (read BatchRegistry contract) 

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch9.buidlguidl.com#4]
## Goal

Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract (see #10)
- Each builder should link to their personal profile (see #9)

**Comment by arjanjohan** [comment]
Also I just made a simple list of addresses, that link to builder profile. Maybe we could extract the ENS profile picture and display some nice cards instead. What do you guys think?

**Comment by danitome24** [comment]
@arjanjohan The `BatchRegistry.sol` contract allows to checkIn multiple times but only the first time it will send you the reward. If you use events for checking who checkedIn, you can filer for `wasFirstTime` param equals `true`.

```tsx
const {
  data: events,
  isLoading: isLoadingEvents,
  error: errorReadingEvents,
} = useScaffoldEventHistory({
  contractName: "BatchRegistry",
  eventName: "CheckedIn",
  fromBlock: 31231n,
  watch: true,
  filters: { first: true },
  blockData: true,
  transactionData: true,
  receiptData: true,
});
```

You will get wallets not duplicated I think. Hope it helps

**Comment by danitome24** [comment]
@arjanjohan can you submit a PR so I can help you with the development process? What do you think about it?

**Comment by danitome24** [comment]
Hi, I started working on this issue. I will post a PR in case somebody else want to help :)
