### ISSUE TITLE
5. Get the check-in count from the BatchRegistry contract

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch9.buidlguidl.com#6]
## Goal

There is a "To Be implemented" string in `packages/nextjs/app/page.tsx` that should show the number of builders that have checked in to the contract.

We want to show the real count (reading from the BatchRegistry contract)

For more info about the contract: https://github.com/BuidlGuidl/batch9.buidlguidl.com/issues/10

**Comment by fedeloterstein** [comment]
I'm going to add this call to the smart contract. Is there a specific design that needs to be used?

**Comment by fedeloterstein** [comment]
I [finished a PR ](https://github.com/BuidlGuidl/batch9.buidlguidl.com/pull/15)getting the data and validating that it doesn't show empty when there is no data
