### ISSUE TITLE
3. Change the Logo / title / subtitle

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch9.buidlguidl.com#8]
## Goal

Update your batch's mainpage. 

![284656861-52a77020-0c08-4136-8cc5-244bc3bd088a](https://github.com/BuidlGuidl/batch2.buidlguidl.com/assets/2486142/f9d3495a-9946-4b8e-ac55-8e00cdc380e0)

- Create a random logo (or use Dall-E!) to generate a batch logo
- title: Batch #{batch_number}
- subtitle: Whatever you feel appropriate :)

**Comment by fedeloterstein** [comment]
I'm working on this Issue!

**Comment by fedeloterstein** [comment]
> I'm working on this Issue!

Completed in [this PR](https://github.com/BuidlGuidl/batch9.buidlguidl.com/pull/14) 🏗️

**Comment by arjanjohan** [comment]
I completed this PR here: https://github.com/BuidlGuidl/batch9.buidlguidl.com/pull/18

**Comment by guidoPeirano** [comment]
Although I really like the sober style chosen by @fedeloterstein, I find @arjanjohan 's design to be more fun. I think we could deffinitely go that way!
